### ISSUE TITLE
Show Empty Buttons broken

### ISSUE THREAD

**Issue by SajuukCor** [tullamods/Dominos#795]
The buttons when "Show Empty Buttons" is enabled are not showing. You have to turn off and then back on the option to show the empty button spaces. You have to do this every login or reload of the UI.

**Addon Version**
10.2.5-beta2
(10.2.1 works)

**World of Warcraft Version**
Retail 10.2.5

**Comment by Tuller** [comment]
This should be fixed in the next beta release (10.2.5-beta4)

**Comment by kirkwor** [comment]
Not sure if from this fix or not, but the Action Bar 1 keeps disappearing, either in full or random buttons, same happens when you take portals in cities or zone in into instances.

**Comment by Tuller** [comment]
Still trying to replicate this one. Are you using the beta versions?

**Comment by kirkwor** [comment]
@Tuller 

Yes, it was the beta version and now I've installed the new release which fixes the empty buttons, but the bar is still broken.

To test you can mount on your dragon-riding mount (as that changes your "actionbar 1") and take a portal (to Emerald Dream from Valdrakken) or zone into an instance (e.g. Dawn of the Infinite). All buttons on bar 1 will disappear, but they're still there if you press 1, 2, 3, 4, 5, etc. it will reveal them. So it seems to just disappear visually? 

Let me know if I can provide you with more info.

**Comment by Tuller** [comment]
10.2.6 should resolve. I’m forcing a visibility update whenever you enter a new area

**Comment by kirkwor** [comment]
Can confirm that has fixed it, cheers!
