### ISSUE TITLE
Action Bars configuration doesn't work

### ISSUE THREAD

**Issue by ondrackajan** [tullamods/Dominos#806]
When I try to change the settings of action bars (1-10) by right click, nothing happens. 
When I do the same to any other bars - rolls, mirror, cast, pet, xp etc, it shows the settings normally. I haven't changed any setting in the addon yet.

**Addon Version**
10.2.7

**World of Warcraft Version**
WOTKL 3.4.3

**Comment by Tuller** [comment]
This should be resolved in 10.2.8

**Comment by wrecka** [comment]
I am on retail 10.2.5 dominos 10.2.8 and It does not work still. Right clicking and selecting any dropdown menu on bars give the following error.

```
1x ..._Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1512: attempt to index field 'NewFeature' (a nil value)
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1512: in function `UIDropDownMenu_Refresh'
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1580: in function `UIDropDownMenu_SetSelectedValue'
[string "@Dominos_Config/widgets/dropdown.lua"]:83: in function `ShowMenu'
[string "@Dominos_Config/widgets/dropdown.lua"]:42: in function `initFunction'
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:771: in function `UIDropDownMenu_Initialize'
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1781: in function `ToggleDropDownMenu'
[string "@Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:686: in function <..._Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:683>

Locals:
self = <table> {
 UIDropDownMenu_SetButtonText = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2085
 containsMouse = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1920
 UIDropDownMenu_DisableButton = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2069
 Create_UIDropDownCustomMenuEntry = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2293
 UIDropDownMenu_Refresh = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1448
 UIDropDownMenu_Initialize = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:762
 UIDropDownMenu_SetSelectedName = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1568
 UIDropDownMenu_SetDropDownEnabled = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2111
 UIDropDownMenu_SetInitializeFunction = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:789
 UIDropDownMenu_GetSelectedID = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1594
 UIDropDownMenu_MatchTextWidth = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1953
 DropDownExpandArrowMixin = <table> {
 }
 UIDropDownMenuButton_ShouldShowIconTooltip = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:118
 UIDropDownMenu_InitializeHelper = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:92
 DropDownMenuButtonMixin = <table> {
 }
 UIDropDownMenuButton_GetName = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2055
 UIDropDownMenu_ClearAll = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2000
 UIDropDownMenu_GetCurrentDropDown = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2043
 UIDropDownMenu_JustifyText = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2019
 UIDropDownMenu_IsEnabled = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2160
 UIDropDownMenu_RefreshDropDownSize = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:820
 UIDropDownMenu_EnableButton = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2073
 UIDropDownMenu_SetFrameStrata = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:816
 UIDropDownMenu_AddButton = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:985
 UIDropDownMenu_GetButtonWidth = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1400
 CloseDropDownMenus = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1881
 UIDropDownMenu_HandleGlobalMouseEvent = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1925
 ColorPicker_GetPreviousValues = <function> defined @WeakAuras/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2158
 Create_UIDropDownMenu = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:748
 UIDropDownMenu_SetButtonWidth = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1980
 UIDropDownCustomMenuEntryMixin = <table> {
 }
 UIDropDownMenuButton_OpenColorPicker = <function> defined @Dominos_Config/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2059
 UIDropDownMenu_AddSeparator = <function> defined @AddOn
```

**Comment by Tuller** [comment]
Applied one more library update in 10.2.9 to resolve

**Comment by wrecka** [comment]
Just figured I'd update. Still does not work. deleted all saved variables, reinstaled and loaded up again. No luck.
